#!/usr/bin/bash


export PICONTROLLER_CONFIGURATION_PATH=$1
source ./scripts/export_variables
./scripts/install_mqtt_on_hub
./scripts/install_python_packages
./scripts/setup_systemd_picontroller_service
./scripts/setup_systemd_picontrollerserver_service

