#!/usr/bin/bash

./scripts/send.sh humidity_sensor:read
./scripts/send.sh moisture_sensor:read

sleep 1
./scripts/send.sh water_servo:up
sleep 1
./scripts/send.sh water_servo:down

# TODO: fix swing function
# sleep 1
# ./scripts/send.sh water_servo:swing

sleep 1
./scripts/send.sh light_servo:up
sleep 1
./scripts/send.sh light_servo:down
sleep 1
./scripts/send.sh light_servo:down

# TODO: fix swing function
# sleep 1
# ./scripts/send.sh light_servo:swing

./scripts/send.sh builtin_led:blink
