#!/usr/bin/bash

sudo cp $PICONTROLLER_PROJECT_PATH/systemd_services/picontroller.service /etc/systemd/system/picontroller.service
sudo systemctl daemon-reexec
sudo systemctl daemon-reload
sudo systemctl enable picontroller.service
sudo systemctl start picontroller.service
