#!/usr/bin/bash

sudo cp $PICONTROLLER_PROJECT_PATH/systemd_services/picontrollerserver.service /etc/systemd/system/picontrollerserver.service
sudo systemctl daemon-reexec
sudo systemctl daemon-reload
sudo systemctl enable picontrollerserver.service
sudo systemctl start picontrollerserver.service
