#!/usr/bin/bash


echo "Installingg picontrollerserver.service"
./scripts/export_variables

envsubst < $PICONTROLLER_PROJECT_PATH/systemd_services/picontrollerserver.service.template | sudo tee /etc/systemd/system/picontrollerserver.service > /dev/null

sudo systemctl daemon-reexec
sudo systemctl daemon-reload
sudo systemctl enable picontrollerserver.service
sudo systemctl start picontrollerserver.service
echo "picontrollerserver.service installed and enabled"

