#!/usr/bin/bash

$PICONTROLLER_PROJECT_PATH/scripts/send.sh humidity_sensor:read
$PICONTROLLER_PROJECT_PATH/scripts/send.sh moisture_sensor:read

sleep 1
$PICONTROLLER_PROJECT_PATH/scripts/send.sh water_servo:up
sleep 1
$PICONTROLLER_PROJECT_PATH/scripts/send.sh water_servo:down

# TODO: fix swing function
# sleep 1
# $PICONTROLLER_PROJECT_PATH/scripts/send.sh water_servo:swing

sleep 1
$PICONTROLLER_PROJECT_PATH/scripts/send.sh light_servo:up
sleep 1
$PICONTROLLER_PROJECT_PATH/scripts/send.sh light_servo:down
sleep 1
$PICONTROLLER_PROJECT_PATH/scripts/send.sh light_servo:down

# TODO: fix swing function
# sleep 1
# $PICONTROLLER_PROJECT_PATH/scripts/send.sh light_servo:swing

$PICONTROLLER_PROJECT_PATH/scripts/send.sh builtin_led:blink
